# SUP ML 3 - PREDICT

#### **Nombres**:
      Albert Fernández
      Julieta Kaplan
      Roger Torruella Vilchez
      Rory Thomson Nelson
      Santiago Ezequiel Velasco
#### **Fecha**: 27/12/2024

# Librerias

In [ ]:
pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 4.6 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# modelos
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier # Stochastic Gradient Descent Classifier: el equivalente del Adaline
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier

# metricas
import sklearn.metrics as metrics

# interpretabilidad
import shap

# para visualizar mas columnas en un df
pd.set_option('display.max_columns',None)

import warnings
warnings.filterwarnings("ignore")  # inhabilita warnings

np.random.seed(42)

# Carga modelo

* Cargar el modelo
* Obtener la lista de model features

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
modelo = pd.read_pickle("/content/drive/MyDrive/DSC0924 – Entregable 2 - Fernández-Kaplan-Torruella-Thomson-Velasco/Pickle/modelo.pkl")


In [ ]:
scaler = pd.read_pickle("/content/drive/MyDrive/DSC0924 – Entregable 2 - Fernández-Kaplan-Torruella-Thomson-Velasco/Pickle/scaler.pkl")

In [ ]:
customer_id = pd.read_pickle('/content/drive/MyDrive/DSC0924 – Entregable 2 - Fernández-Kaplan-Torruella-Thomson-Velasco/Pickle/df_pred_Customer_ID.pkl')

In [ ]:
print(f'Importanción del modelo {modelo}, y de la columna customer_id', '\n', customer_id, f'del anterior notebook ')

Importanción del modelo <catboost.core.CatBoostClassifier object at 0x7ae0c0ebfc10>, y de la columna customer_id 
 0       1090001
1       1090002
2       1090003
3       1090004
4       1090005
         ...   
8455    1099982
8456    1099985
8457    1099986
8458    1099987
8459    1099994
Name: Customer_ID, Length: 8460, dtype: int64 del anterior notebook 


# Carga PREDICT dataset

In [ ]:
df_predecir=pd.read_pickle('/content/drive/MyDrive/DSC0924 – Entregable 2 - Fernández-Kaplan-Torruella-Thomson-Velasco/Pickle/ML1_Processing_pred.pkl')

In [ ]:
df_predecir

HHstatin_C  HHstatin_I  HHstatin_Otros  HHstatin_UNKW  actvsubs  \
0              1           0               0              0         1   
1              0           0               0              1         1   
2              1           0               0              0         2   
3              0           0               0              1         1   
4              1           0               0              0         1   
...          ...         ...             ...            ...       ...   
8455           1           0               0              0         1   
8456           1           0               0              0         2   
8457           1           0               0              0         1   
8458           1           0               0              0         1   
8459           0           0               0              1         1   

       adjmou  adjqty   adjrev    adults  area_AS  area_C  area_CN  area_CST  \
0       958.0     393   182.94  1.000000        1       0        0         0   
1      3998.0    1634   305.59  2.459525        0       0        0         0   
2      1772.0     734   219.45  3.000000        0       0        0         1   
3     18478.0    9018  2131.17  3.000000        1       0        0         0   
4      2601.0     791   608.66  1.000000        0       0        0         0   
...       ...     ...      ...       ...      ...     ...      ...       ...   
8455   4489.0    1011   920.36  1.000000        0       0        0         0   
8456   7137.0    1549  1481.10  2.000000        0       0        0         0   
8457  14628.0    5375  1786.73  2.000000        0       0        0         0   
8458   3373.0    2663   902.54  1.000000        0       0        0         0   
8459  19032.0    8392  1931.72  4.000000        0       0        0         0   

      area_D  area_DMV  area_GL  area_H  area_LA  area_M  area_NE  area_NF  \
0          0         0        0       0        0       0        0        0   
1          0         0        0       0        0       0        0        0   
2          0         0        0       0        0       0        0        0   
3          0         0        0       0        0       0        0        0   
4          0         0        0       0        1       0        0        0   
...      ...       ...      ...     ...      ...     ...      ...      ...   
8455       0         0        0       0        1       0        0        0   
8456       0         0        0       0        1       0        0        0   
8457       0         0        0       0        1       0        0        0   
8458       0         0        0       0        1       0        0        0   
8459       0         0        0       0        1       0        0        0   

      area_NRM  area_NYC  area_O  area_P  area_S  area_SF  area_T  asl_flag  \
0            0         0       0       0       0        0       0         0   
1            1         0       0       0       0        0       0         1   
2            0         0       0       0       0        0       0         0   
3            0         0       0       0       0        0       0         0   
4            0         0       0       0       0        0       0         1   
...        ...       ...     ...     ...     ...      ...     ...       ...   
8455         0         0       0       0       0        0       0         0   
8456         0         0       0       0       0        0       0         0   
8457         0         0       0       0       0        0       0         0   
8458         0         0       0       0       0        0       0         0   
8459         0         0       0       0       0        0       0         0   

      avg3qty  avg3rev  avg6rev   avgmou  avgqty  avgrev  blck_dat   blck_vce  \
0          52       30     31.0   159.67   65.50   30.49       0.0  10.333333   
1         181       48     51.0   666.33  272.33   50.93       0.0   0.000000   
2         107       30     31.0   253.1

# ML Preprocessing

Se deben realizar las mismas transformaciones que se aplicaron en el preprocessing del train:
  * Eliminar mismas variables
  * Imputar mismos valores a nulos
  * Aplicar mismo encoding de categoricos
  * ...todo lo necesario para replicar las variables con las que el modelo se entrenó

NO SE DEBEN repetir:
  * Analisis visual de los datos
  * Analisis de correlaciones
  * Analisis de varianza
  * Calculo de metricas que varien con la distribución

In [ ]:
# Al haber hecho el mismo datacleaning en el ML_1, no tenemos que hacerlo ahora.

# Check model features

* Comprobar que tenemos en el dataset preprocesado todas las model features, de lo contrario no podremos hacer predict.
* Ordenar las variables en mismo orden que las model features

In [ ]:
# Ya se hizo en el ML_2.

# Rescaling

* Si se entrenó el modelo con un dataset estandarizado, estandarizar con mismo scaler.

In [ ]:
# se estandarizaran las variables del df a predecir con los parametros calculados en el X_train
df_predecir = scaler.transform(df_predecir)

In [ ]:
df_predecir

array([[ 1.15883529, -0.39550131, -0.35651631, ..., -0.36480318,
        -0.46666846, -0.42710508],
       [-0.86293541, -0.39550131, -0.35651631, ..., -0.45597435,
        -0.46666846, -0.14266888],
       [ 1.15883529, -0.39550131, -0.35651631, ..., -0.1642266 ,
         0.37476711, -0.44444875],
       ...,
       [ 1.15883529, -0.39550131, -0.35651631, ..., -0.09128966,
        -0.46666846, -0.4068708 ],
       [ 1.15883529, -0.39550131, -0.35651631, ...,  0.00899863,
        -0.46666846,  2.59069362],
       [-0.86293541, -0.39550131, -0.35651631, ...,  0.40103467,
        -0.46666846, -0.05421616]])

# PREDICT

* predict() y predict_proba()

In [ ]:
# Creamos un array con las predicciones del modelo (en unos y ceros)
pred = modelo.predict(df_predecir)
print(f' El resultado del la predicción esta en formato array', '\n',  pred)

 El resultado del la predicción esta en formato array 
 [0 0 0 ... 0 1 0]


In [ ]:
# Creamos un array con las predicciones del modelo (en porcentaje en base uno)
pred_proba = modelo.predict_proba(df_predecir)
pred_proba
print(f' El resultado del la probabilidad de la prediccion esta en formato array', '\n',  pred_proba, '\n', 'Este array es el porcentage sin redondeo del que extraemos la prediccion' )

 El resultado del la probabilidad de la prediccion esta en formato array 
 [[0.61014368 0.38985632]
 [0.55522558 0.44477442]
 [0.86557913 0.13442087]
 ...
 [0.58425826 0.41574174]
 [0.43072946 0.56927054]
 [0.60144035 0.39855965]] 
 Este array es el porcentage sin redondeo del que extraemos la prediccion


In [ ]:
# Formateamos las predicciones en probabilidad, redondeando para omitir decimales innecesarios
pred_proba2 = np.round(pred_proba[:,1]*100,1)
print(f' El resultado del la probabilidad de la prediccion esta en formato array', '\n',  pred_proba2, '\n', 'Este array es el porcentage con redondeo del que extraemos la prediccion' )

 El resultado del la probabilidad de la prediccion esta en formato array 
 [39.  44.5 13.4 ... 41.6 56.9 39.9] 
 Este array es el porcentage con redondeo del que extraemos la prediccion


In [ ]:
# Creamos un dataframe con las predicciones y las probabilidades
df_prediccion = pd.DataFrame()
df_prediccion['Customer_ID'] = customer_id
df_prediccion['prediccion'] = pred
df_prediccion['%_proba'] = pred_proba2
print(f'{df_prediccion}','\n','Podemos ver la prediccion de cada cliente junto a la probabilidad de la prediccion')
df_prediccion


      Customer_ID  prediccion  %_proba
0         1090001           0     39.0
1         1090002           0     44.5
2         1090003           0     13.4
3         1090004           0     48.7
4         1090005           0     34.6
...           ...         ...      ...
8455      1099982           1     54.8
8456      1099985           0     20.9
8457      1099986           0     41.6
8458      1099987           1     56.9
8459      1099994           0     39.9

[8460 rows x 3 columns] 
 Podemos ver la prediccion de cada cliente junto a la probabilidad de la prediccion


Customer_ID  prediccion  %_proba
0         1090001           0     39.0
1         1090002           0     44.5
2         1090003           0     13.4
3         1090004           0     48.7
4         1090005           0     34.6
...           ...         ...      ...
8455      1099982           1     54.8
8456      1099985           0     20.9
8457      1099986           0     41.6
8458      1099987           1     56.9
8459      1099994           0     39.9

[8460 rows x 3 columns]

In [ ]:
df_prediccion['prediccion'].value_counts()

prediccion
0    6210
1    2250
Name: count, dtype: int64

# Guarda predicciones

* Guardar las predicciones en data path. Cada fila debe estar etiquetada con el ID.

In [ ]:
df_prediccion.to_csv("/content/drive/MyDrive/DSC0924 – Entregable 2 - Fernández-Kaplan-Torruella-Thomson-Velasco/OUTPUT FINAL_PREDICCIONES.csv")